# Generated by Django 5.1.2 on 2024-11-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('hashed_password', models.CharField(max_length=255)),
                ('encryption_method', models.CharField(choices=[('bcrypt', 'Bcrypt'), ('sha256', 'SHA-256'), ('fernet', 'Fernet')], max_length=10)),
            ],
        ),
    ]
